

#pragma once

namespace hh
{
	namespace errors
	{
		enum error_t : int
		{
			success              = 0,
			invalid_function     = 1,
			file_not_found       = 2,
			path_not_found       = 3,
			invalid_handle       = 6,
			not_enough_memory    = 8,
			invalid_block        = 9,
			bad_environment      = 10,
			bad_format           = 11,
			invalid_access       = 12,
			invalid_data         = 13,
			out_of_memory        = 14,
			invalid_drive        = 15,
			no_more_files        = 18,
			write_protect        = 19,
			bad_unit             = 20,
			not_ready            = 21,
			bad_command          = 22,
			crc                  = 23,
			bad_length           = 24,
			write_fault          = 29,
			read_fault           = 30,
			not_supported        = 50,
			network_busy         = 54,
			file_exists          = 80,
			can_not_make         = 82,
			invalid_password     = 86,
			invalid_parameter    = 87,
			drive_locked         = 108,
			open_failed          = 110,
			buffer_overflow      = 111,
			disk_full            = 112,
			invalid_name         = 123,
			invalid_level        = 124,
			lock_failed          = 167,
			busy                 = 170,
			already_exists       = 183,
			locked               = 212,
			bad_file_type        = 222,
			file_too_large       = 223,
			no_data              = 232,
			wait_timeout         = 258,
			no_more_items        = 259,
			can_not_copy         = 266,
			control_c_exit       = 572,
			app_init_failure     = 575,
			password_too_short   = 615,
			system_shutdown      = 641,
			password_too_long    = 657,
			io_incomplete        = 996,
			io_pending           = 997,
			stack_overflow       = 1001,
			invalid_message      = 1002,
			can_not_complete     = 1003,
			invalid_flags        = 1004,
			invalid_block_length  = 1106,
			invalid_dll           = 1154,
			dll_not_found         = 1157,
			no_network            = 1222,
			continue_             = 1246,
			already_initialized   = 1247,
			host_down             = 1256,
			user_exists           = 1316,
			wrong_password        = 1323,
			account_disabled      = 1331,
			invalid_index         = 1413,
			screen_already_locked = 1440,
			invalid_command_line  = 1639,
			invalid_datatype      = 1804,
			invalid_environment   = 1805,
			bad_username          = 2202,
			empty                 = 4306,
			not_empty             = 4307,
			object_not_found      = 4312,
			invalid_operation     = 4317
		};
	}
}